use std::collections::HashSet;
use std::sync::LazyLock;

pub const RESERVED: &[&str] = &[
    "and",
    "or",
    "not",
    "not=",
    "lshift",
    "rshift",
    "band",
    "bor",
    "bxor",
    "bnot",
    "length",
    "->",
    "->>",
    "-?>",
    "-?>>",
    "fn",
    "lambda",
    "λ",
    "local",
    "let",
    "set",
    "global",
    "include",
    "accumulate",
    "catch",
    "collect",
    "icollect",
    "fcollect",
    "do",
    "doto",
    "each",
    "eval-compiler",
    "for",
    "if",
    "import-macros",
    ":into",
    "lua",
    "macro",
    "macrodebug",
    "macros",
    "match",
    "match-try",
    "partial",
    "pick-args",
    "values",
    "pick-values",
    "require-macros",
    "tset",
    ":until",
    "&until",
    "var",
    "when",
    "where",
    "while",
    "with-open",
];

pub const KEYWORDS: &[&str] = &[
    "->",
    "->>",
    "-?>",
    "-?>>",
    "fn",
    "lambda",
    "λ",
    "local",
    "let",
    "set",
    "global",
    "include",
    "accumulate",
    "catch",
    "collect",
    "icollect",
    "fcollect",
    "do",
    "doto",
    "each",
    "eval-compiler",
    "for",
    "if",
    "import-macros",
    "lua",
    "macro",
    "macrodebug",
    "macros",
    "match",
    "match-try",
    "partial",
    "pick-args",
    "values",
    "pick-values",
    "require-macros",
    "tset",
    "var",
    "when",
    "where",
    "while",
    "with-open",
];

pub const OPERATORS: &[&str] =
    &["and", "or", "not", "not=", "lshift", "rshift", "band", "bor", "bxor", "bnot", "length"];

pub const LITERALS: &[&str] = &["true", "false", "nil"];

pub const COMPILER_MACROS: &[&str] = &[
    "list",
    "sym",
    "gensym",
    "list?",
    "sym?",
    "table?",
    "sequence?",
    "varg?",
    "multi-sym?",
    "comment?",
    "view",
    "get-scope",
    "assert-compile",
    "in-scope?",
    "macroexpand",
];

pub static RESERVED_SET: LazyLock<HashSet<&'static str>> =
    LazyLock::new(|| HashSet::from_iter(RESERVED.iter().copied()));

pub static COMPILER_MACROS_SET: LazyLock<HashSet<&'static str>> =
    LazyLock::new(|| HashSet::from_iter(COMPILER_MACROS.iter().copied()));
